version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
#    volumes:
#      - ./frontend:/app
    command: [ "yarn", "run", "dev" ]